### ISSUE TITLE
アラートの最大保持期間

### ISSUE THREAD

**Issue by kakojima** [MicrosoftDocs/ATADocs.ja-jp#23]
[フィードバックをこちらに入力してください]
アラートの最大保持期間を掲載してほしい。
開発の方にも確認したところ、10 ヶ月間となっておりました。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 518df292-7c68-eafb-c968-d7df3c004b6f
* Version Independent ID: 8a3bd941-a035-a667-705a-3bf593c16536
* Content: [Azure Advanced Threat Protection でのセキュリティ アラートの処理](https://docs.microsoft.com/ja-jp/azure-advanced-threat-protection/working-with-suspicious-activities#feedback)
* Content Source: [ATPDocs/working-with-suspicious-activities.md](https://github.com/MicrosoftDocs/ATADocs.ja-jp/blob/live/ATPDocs/working-with-suspicious-activities.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by CeciAc** [comment]
こんにちは、@kakojima 
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら https://github.com/MicrosoftDocs/ATADocs/issues/219 を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
