### ISSUE TITLE
保護範囲について

### ISSUE THREAD

**Issue by colt-kk** [MicrosoftDocs/ATADocs.ja-jp#24]
[フィードバックをこちらに入力してください]
以下の文言が記載されておりますが、Azure AD への認証は監視しないと思いますので、誤解の無いよう変更いただきたいです。
-------------------------------------
Azure ATP は、オンプレミスの Active Directory ユーザーまたは Azure Active Directory に同期されたユーザー (あるいは両方) を保護します。
-------------------------------------
　↓
-------------------------------------
Azure ATP は、オンプレミスの Active Directory ユーザーまたは Azure Active Directory に同期されたユーザー でのオンプレミス Active DIrectory での認証を保護します。
-------------------------------------
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3e880e6e-9cae-b122-14d9-963eee86d9cc
* Version Independent ID: c8ab5d85-f3a4-2c24-d6c6-5940e26aea42
* Content: [Azure Advanced Threat Protection の前提条件](https://docs.microsoft.com/ja-jp/azure-advanced-threat-protection/atp-prerequisites#feedback)
* Content Source: [ATPDocs/atp-prerequisites.md](https://github.com/MicrosoftDocs/ATADocs.ja-jp/blob/live/ATPDocs/atp-prerequisites.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by srvbpigh** [comment]
Hello, @colt-kk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
