### ISSUE TITLE
About Azure ATP sensor network entity resolution

### ISSUE THREAD

**Issue by kahosoka** [MicrosoftDocs/ATADocs.ja-jp#25]
[フィードバックをこちらに入力してください]
"Resolve network entities (users, groups, computers)" in the Azure ATP sensor description, please provide details here.
■Contents to be described
・What exactly does user name, group name, and computer name resolution do?
・Which values are used specifically to resolve user names, group names, and computer names?

If you do not provide this information, we will not be able to accurately provide you with Azure ATP, so please cooperate.

![image](https://user-images.githubusercontent.com/59992995/72595160-89c66600-394c-11ea-8a74-17b0fcd69835.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e6e1c17a-2f22-6a6f-d5ba-bedda3984aef
* Version Independent ID: 8531caef-8ef2-1f45-6362-0c83bd1de9dc
* Content: [Azure Advanced Threat Protection のアーキテクチャ](https://docs.microsoft.com/ja-jp/azure-advanced-threat-protection/atp-architecture#feedback)
* Content Source: [ATPDocs/atp-architecture.md](https://github.com/MicrosoftDocs/ATADocs.ja-jp/blob/live/ATPDocs/atp-architecture.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by srvbpigh** [comment]
Hello, @kahosoka
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @kahosoka, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/ATADocs/issues/278. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
